font-family = "HackGen Console NF"
font-size = 19
adjust-cell-height = 20%

window-width = 130
window-height = 28

background-opacity = 1.0

macos-option-as-alt = true

theme = GitHub Dark High Contrast

shell-integration = detect 
